language: python
python:
  - "3.6" 
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_db;' -U kc
# command to run tests
script:
  - pytest
